// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqndtqhzuooyiwqdfmzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxbmR0cWh6dW9veWl3cWRmbXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjY5NDIsImV4cCI6MjA2NjI0Mjk0Mn0.IyyznWTmuYITOJvFpLsiI6J51pPCB5-55sIyQN-hZrM";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true, // Optional, for OAuth or redirect flows
    },
  }
);